### ISSUE TITLE
The example doesn't load on a fully updated Meta Quest Pro

### ISSUE THREAD

**Issue by EricMoerthVis** [meta-quest/reality-accelerator-toolkit#4]
It doesn't matter how I start it (hand tracking, one controller or two controllers) the page doesn't load, is either stuck with the three dots or just leaves a blank gray page.

**Comment by diarmidmackenzie** [comment]
I've been using this on Quest Pro.  The page loads, but on entering AR mode, I just get a black screen.

Console error as follows:
```
DOMException: Failed to execute 'requestReferenceSpace' on 'XRSession': This device does not support the requested reference space type.
```

I have been able to fix this by adding 'local-floor' to the list of `requiredFeatures` in `ARButton.convertToARButton`.

**Comment by felixtrz** [comment]
Thank you for your feedback, closing issue as this seems to be fixed by @diarmidmackenzie's PR.
