### ISSUE TITLE
[Feature Request] Bundle library to be consumable over CDN

### ISSUE THREAD

**Issue by msub2** [meta-quest/reality-accelerator-toolkit#6]
Given that this library code has no hard dependencies on any other third-party libraries, it would be super helpful to let people import it through a CDN (unpkg, jsdelivr, etc). Currently though the library isn't being bundled, just compiled with tsc, so you can only consume it as an NPM package.

**Comment by felixtrz** [comment]
Thanks for your feedback, will provide a bundled version soon

**Comment by msub2** [comment]
Thanks! I see the necessary build changes were pushed, will close this now.
