### ISSUE TITLE
How to activate the mesh detection and see the 3D objects in the display monitor?

### ISSUE THREAD

**Issue by Carton22** [meta-quest/reality-accelerator-toolkit#7]
I have clicked into [this demo](https://meta-quest.github.io/reality-accelerator-toolkit/example/), but I am only able to see the real world in Meta Quest Pro and my predefined room including walls and ceiling. But when I look at my computer monitor and pinch my fingers, there is nothing showing up. I could not see the purple background and the inner 3D geometrical object shown in the [video](https://youtu.be/M2QTwirp-B8?si=hcQV4mrt9RONAiq8&t=674). Is there anything wrong?

**Comment by msub2** [comment]
I believe that demo was created for the video and is not the same one as the example app in this repo.

**Comment by felixtrz** [comment]
Correct, the demo in the video is actually available here: https://github.com/felixtrz/blazoid, deployed at https://felixtrz.github.io/blazoid/
For this to work as intended, you'd have to go through the Physical Space setup and manually mark out your desk and monitor.
