### ISSUE TITLE
Hit exception on leaving and re-entering AR

### ISSUE THREAD

**Issue by diarmidmackenzie** [meta-quest/reality-accelerator-toolkit#8]
To reproduce::
- with a room setup in place...
- open the example page: https://meta-quest.github.io/reality-accelerator-toolkit/example/
- enter AR
- place some anchors (trigger)
- exit AR
- re-enter AR.

Hit exception as follows:

```
Uncaught DOMException: Failed to execute 'getPose' on 'XRFrame': XRSpace and XRFrame sessions do not match.
    at updateTransformObject (https://meta-quest.github.io/reality-accelerator-toolkit/example/index.bundle.js:567:24)
    at https://meta-quest.github.io/reality-accelerator-toolkit/example/index.bundle.js:390:57
    at Set.forEach (<anonymous>)
    at RealityAccelerator.update (https://meta-quest.github.io/reality-accelerator-toolkit/example/index.bundle.js:389:22)
    at render (https://meta-quest.github.io/reality-accelerator-toolkit/example/index.bundle.js:115317:7)
    at onAnimationFrame (https://meta-quest.github.io/reality-accelerator-toolkit/example/index.bundle.js:83532:36)
    at XRSession.onAnimationFrame (https://meta-quest.github.io/reality-accelerator-toolkit/example/index.bundle.js:70278:3)
    
```

The issue seems to be that the TransformObject for the anchor stores off `this._xrSpace` on creation ([here](https://github.com/meta-quest/reality-accelerator-toolkit/blob/a7ae03e1b234c23feef2097d4ae8dd6d5f14c63a/src/TransformObject.ts#L17)).  It becomes invalid when the XR session ends and restarts, but the reference is retained, leading to the above error in [`updateTransformObject`](https://github.com/meta-quest/reality-accelerator-toolkit/blob/a7ae03e1b234c23feef2097d4ae8dd6d5f14c63a/src/TransformObject.ts#L34C15-L34C15).

My guess is that `this._xrSpace` needs to be updated when the new XR session begins.  I am looking at this further to try to determine how this can be fixed.

**Comment by diarmidmackenzie** [comment]
My initial assumption was that Anchors could persist from one session to the next, and it was just the saved-off xrSpace reference that was stale.

That proved to be incorrect.  In fact XRAnchors are created within the context of a session, so when the session changes, the old anchors are lost and need to be recreated.

Current model is that the call to `restorePersistentAnchors()` is made from the app that uses ratk, so seems cleanest to leave that responsibility with the app in all cases, meaning that the app must re-call `restorePersistentAnchors()` for each new WebXR session.

The only change required to ratk itself is to clear out stale state (e.g. the list of XRAnchors, which no longer exist), on detection of a new session.

Similar issues arise with HitTestTargets, Planes and Meshes.

With Planes and Meshes, the existing "diff" logic seems to take care of clearing out any stale Planes/Meshes.

With HitTestTargets, similarly to Anchors, there will be stale state left in ratk that needs to be cleared out on detection of a change of XRSession.

I've made & tested these changes and they seem to fix the problem, so I will submit a PR.

**Comment by diarmidmackenzie** [comment]
#9 offers a fix for this.

**Comment by felixtrz** [comment]
Thank you for your contribution, I will review and merge the PR

**Comment by felixtrz** [comment]
Approved and merged, closing issue.
